# ===============================
# = APP INFO
# ===============================
app:
  name: ${APP_NAME:app}
  version: ${APP_VER:0.2.1}
  url: ${APP_URL:http://domain.com}
# ===============================
# = SPRING
# ===============================
spring:
  application:
    name: Price Mysql
  main:
    banner-mode: 'off'
  profiles:
    active: dev
# ===============================
# = WEB
# ===============================
server:
  port: 8090
  servlet:
    context-path: ${CONTEXT_PATH:/}
# ===============================
# = LOGGING
# ===============================
logging:
  level:
    root: info
    sql:  info
    web:  info
# ===============================
# = DOWNLOAD
# ===============================
download:
  query:
    value:
      login: ${DL_LOGIN:login}
      password: ${DL_PASS:pass}
    param:
      login: ${DL_PARAM_LOGIN:param-login}
      password: ${DL_PARAM_PASS:param-password}
      others: ${DL_PARAM_OTHERS:&AUTH_FORM=Y&TYPE=AUTH}
  url:
    auth: ${DL_AUTH_PATH:http://url/signin/}
    file: ${DL_FILE_PATH:http://url/csv/}
# ===============================
# = USER
# ===============================
user:
  view:
    login: ${USER_VIEW_LOGIN:login}
    pass: ${USER_VIEW_PASS:pass}
  add:
    login: ${USER_ADD_LOGIN:login}
    pass: ${USER_ADD_ASS:pass}
# ===============================
# = WEB
# ===============================
web:
  query: ${QUERY:http://domain.com/?query=}
# ===============================
# = FINANCE
# ===============================
price:
  our-discount: ${OUR_DISCOUNT:10}

---
spring:
  profiles: dev
  # ===============================
  # = DATASOURCE
  # ===============================
  datasource:
    url: jdbc:h2:mem:db
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
  # ===============================
  # = H2 Settings
  # ===============================
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
---
spring:
  profiles: prod
  h2:
    console:
      enabled: false
  # ===============================
  # = DATASOURCE
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME:price_db}?useUnicode=true&characterEncoding=utf-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER:price_user}
    password: ${DB_PASS:price_pass}
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false

  flyway:
    url: jdbc:mysql://localhost:3306/${DB_NAME:price_db}?useUnicode=true&characterEncoding=utf-8
    user: ${DB_USER:price_user}
    password: ${DB_PASS:price_pass}
