# ===============================
# = APP INFO
# ===============================
app:
  name: ${APP_NAME:app}
  version: ${APP_VER:0.2.0}
  url: ${APP_URL:http://domain.com}
# ===============================
# = SPRING
# ===============================
spring:
  application:
    name: Price H2
  main:
    banner-mode: 'off'
  # ===============================
  # = DATASOURCE
  # ===============================
  datasource:
    url: jdbc:h2:mem:db
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  # ===============================
  # = JPA / HIBERNATE
  # ===============================
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
  # ===============================
  # = H2 Settings
  # ===============================
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
# ===============================
# = WEB
# ===============================
server:
  port: 8090
# ===============================
# = LOGGING
# ===============================
logging:
  level:
    root: info
    sql:  info
    web:  info
# ===============================
# = DOWNLOAD
# ===============================
download:
  query:
    value:
      login: ${DL_LOGIN:login}
      password: ${DL_PASS:pass}
    param:
      login: ${DL_PARAM_LOGIN:param-login}
      password: ${DL_PARAM_PASS:param-password}
  url:
    auth: ${DL_AUTH_PATH:http://url/signin/}
    file: ${DL_FILE_PATH:http://url/csv/}
# ===============================
# = USER
# ===============================
user:
  login: ${LOGIN:login}
  pass: ${PASS:pass}
# ===============================
# = WEB
# ===============================
web:
  query: ${QUERY:http://domain.com/?query=}
# ===============================
# = FINANCE
# ===============================
price:
  our-discount: ${OUR_DISCOUNT:10}
