# ===============================
# = APP INFO
# ===============================
app:
  name: ${APP_NAME:app}
  version: ${APP_VER:0.3.0}
  url: ${APP_URL:http://domain.com}

# ===============================
# = SPRING
# ===============================
spring:
  application:
    name: PriceList
  main:
    banner-mode: 'off'
  profiles:
    active: dev

# ===============================
# = WEB
# ===============================
server:
  port: 8090
  servlet:
    context-path: ${CONTEXT_PATH:/}
# ===============================
# = LOGGING
# ===============================
logging:
  level:
    root: info
    sql: info
    web: info
# ===============================
# = DOWNLOAD
# ===============================
download:
  query:
    value:
      login: ${DL_LOGIN:login}
      password: ${DL_PASS:pass}
    param:
      login: ${DL_PARAM_LOGIN:param-login}
      password: ${DL_PARAM_PASS:param-password}
      others: ${DL_PARAM_OTHERS:&AUTH_FORM=Y&TYPE=AUTH}
  url:
    auth: ${DL_AUTH_PATH:http://url/signin/}
    file: ${DL_FILE_PATH:http://url/csv/}
# ===============================
# = USER
# ===============================
default-user:
  login: ${USER_LOGIN:login}
  pass: ${USER_PASS:pass}
# ===============================
# = WEB
# ===============================
web:
  query: ${QUERY:http://domain.com/?query=}
# ===============================
# = FINANCE
# ===============================
price:
  our-discount: ${OUR_DISCOUNT:10}

