# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle Build, Docker Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean unpack
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0
      with:
        # Docker repository to tag the image with:
        repository: vlaship/price-h2
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: ${{ secrets.docker_hub_login }}
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.docker_hub_secret }}
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest
